[package]
name = "ime-monitor"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "ime-monitor"
#crate-type = ["windows"]

[dependencies]
once_cell = "1.19"
hidapi = "2.6"
windows = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_Ime",
    "Win32_UI_Input",
    "Win32_UI_Accessibility",
    "Win32_System_LibraryLoader",
    "Win32_Devices_HumanInterfaceDevice",
    "Win32_Graphics_Gdi",
] }

[profile.release]
lto = true
codegen-units = 1
strip = true
